server:
  port: 8091


eureka:
  client:
    enabled: false
spring:
  cloud:
    zookeeper:
      enabled: false
    consul:
      enabled: false
  application:
    name: discovery-client-demo

--- #Eureka
spring:
  profiles: eureka
eureka:
  server:
    host: http://localhost
    port: 8761
  client:
    register-with-eureka: true
    service-url:
        defaultZone: ${eureka.server.host}:${eureka.server.port}/eureka/
    enabled: true
  instance:
    instance-id: ${sping.application.name}:${server.port}


--- #zookeep
spring:
  profiles: zookeeper
  cloud:
    zookeeper:
      connectString: localhost:2181
      enabled: true

--- # consul
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true








